MODEL:
  TYPE: dat
  NAME: dat_plus_plus
  PRETRAINED: "<path-to-dat_b_in1k.pth>"
  DAT:
    img_size: 224
    patch_size: 4
    num_classes: 1000
    expansion: 4
    dim_stem: 128
    dims: [128, 256, 512, 1024]
    depths: [2, 4, 18, 2]
    stage_spec: [[N, D], [N, D, N, D], [N, D, N, D, N, D, N, D, N, D, N, D, N, D, N, D, N, D], [D, D]]
    heads: [4, 8, 16, 32]
    window_sizes: [7, 7, 7, 7]
    groups: [2, 4, 8, 16]
    use_pes: [True, True, True, True]
    dwc_pes: [False, False, False, False]
    strides: [8, 4, 2, 1]
    offset_range_factor: [-1, -1, -1, -1]
    no_offs: [False, False, False, False]
    fixed_pes: [False, False, False, False]
    use_dwc_mlps: [True, True, True, True]
    use_lpus: [True, True, True, True]
    use_conv_patches: True
    ksizes: [9, 7, 5, 3]
    nat_ksizes: [7, 7, 7, 7]
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.6
    
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 0
  WEIGHT_DECAY: 1.0e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07

TEST:
  CROP: False

DATA:
  BATCH_SIZE: 24
  IMG_SIZE: 384

SAVE_FREQ: 1

